SELECT * FROM customer_behavior LIMIT 10;

--Q1 what is the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer_behavior
group by gender

--Q2 which customer used a discount but still spent more than average purchase amount?
select customer_id , purchase_amount
from customer_behavior
where discount_applied ='Yes' and purchase_amount >=
                                                   (select avg(purchase_amount)
						                             from customer_behavior)


--Q3 which are the top 5 products with the highest avg review rating?
select item_purchased, ROUND(avg(review_rating::numeric),2) as "average product rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4 compare the avg purchase amounts  between  standard and express shipping?
select shipping_type, round(avg(purchase_amount),2)
from customer_behavior
where shipping_type in('Standard', 'Express')
group by shipping_type

--Q5 Do subscriber customers spend more? compare average spend and total revenue
--between subcribers amd non- subcribers.
select subscription_status, round(avg(purchase_amount),2) as avg_spend,
count(customer_id) as total_customer,
round(sum(purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc






													 